# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:

x=s.split()
print (x)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print('The diameter of {one} is {two} kilometers'.format (one=planet,two=diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
d = {
  'k1': [1, 2, 3, {
    'tricky': ['oh', 'man', 'inception', {
      'target': [1, 2, 3, 'hello']
    }]
  }]
}


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array=np.ones(10)
print("An array of 10 ones:")
print(array)


An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
import numpy as np
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 


Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
import numpy as np


a = np.array([1, 2, 3]) 
b = np.array([4,5,6])

np.concatenate((a, b))


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import pandas as pd
pd.date_range(start='1/1/2023', end='10/2/2023', freq='M')


DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30'],
              dtype='datetime64[ns]', freq='M')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists=[[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
df = pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24


In [ ]:
list_2d= [[[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]]
print(list_2d)

[[[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]]
